# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-21 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0011_auto_20190214_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='tipus_de_pagament',
            field=models.CharField(choices=[(b'NO', 'No cal pagament'), (b'EF', 'En efectiu'), (b'EB', "Al caixer de l'entitat banc\xe0ria")], default=b'EB', help_text='Quin ser\xe0 el tipus de pagament predominant', max_length=2),
        ),
    ]
