# Generated by Django 2.1.7 on 2019-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0012_auto_20190221_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='esta_aprovada_pel_consell_escolar',
            field=models.CharField(choices=[('P', 'Pendent'), ('A', 'Aprovada'), ('R', 'Rebutjada'), ('N', 'No necessita aprovació')], default='P', help_text='Marca si aquesta activitat ja ha estat aprovada pel consell escolar', max_length=1, verbose_name='Aprovada_pel_consell_escolar?'),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='estat',
            field=models.CharField(choices=[('E', 'Esborrany'), ('P', 'Proposada'), ('R', 'Revisada pel Coordinador'), ('G', "Gestionada pel Cap d'estudis")], default='E', help_text="Estat de l'activitat. No es considera proposta d'activitat fins que no passa a estat 'Proposada'", max_length=1),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='estat_sincronitzacio',
            field=models.CharField(choices=[('N', 'No sincronitzada'), ('x', ''), ('Y', '')], default='N', editable=False, help_text="Per passar els alumnes a 'no han de ser a l'aula' ", max_length=1),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='mitja_de_transport',
            field=models.CharField(choices=[('TR', 'Tren'), ('BU', 'Bus'), ('AP', 'A peu'), ('CO', 'Combinat'), ('ND', 'No cal desplaçament')], help_text='Tria el mitjà de transport', max_length=2),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='tipus',
            field=models.CharField(choices=[('E', 'Excursió - sortida'), ('X', 'Xerrada'), ('P', 'Parlament Verd'), ('A', 'Altres (especificar-ho al títol)')], default='E', help_text="Tipus d'activitat", max_length=1),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='tipus_de_pagament',
            field=models.CharField(choices=[('NO', 'No cal pagament'), ('EF', 'En efectiu'), ('EB', "Al caixer de l'entitat bancària")], default='EB', help_text='Quin serà el tipus de pagament predominant', max_length=2),
        ),
    ]
