# Generated by Django 2.2 on 2019-07-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0013_auto_20190331_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='preu_per_alumne',
            field=models.DecimalField(decimal_places=2, help_text="Preu per alumne. Indica el preu que apareixerà a l'autorització.", max_digits=5),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='tipus_de_pagament',
            field=models.CharField(choices=[('NO', 'No cal pagament'), ('EF', 'En efectiu'), ('ON', 'Online a través del dJau'), ('EB', "Al caixer de l'entitat bancària")], default='EB', help_text='Quin serà el tipus de pagament predominant', max_length=2),
        ),
    ]
