# Generated by Django 2.2 on 2019-11-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0018_auto_20190816_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagament',
            name='alumne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnes.Alumne'),
        ),
        migrations.AlterField(
            model_name='pagament',
            name='sortida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sortides.Sortida'),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='preu_per_alumne',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Preu per alumne. Indica el preu que apareixerà a l'autorització ( el posa secretaria / coordinador(a) activitats )", max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='tipus_de_pagament',
            field=models.CharField(choices=[('NO', 'No cal pagament'), ('EF', 'En efectiu'), ('EB', "Al caixer de l'entitat bancària")], default='NO', help_text='Quin serà el tipus de pagament predominant', max_length=2),
        ),
    ]
