# Generated by Django 2.2.6 on 2020-02-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0014_auto_20191027_1228'),
        ('sortides', '0019_auto_20191128_1521'),
    ]

    operations = [
    ]
