# Generated by Django 3.0.6 on 2020-06-20 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0011_auto_20191002_1753'),
        ('sortides', '0022_auto_20200223_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comerç',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codi', models.CharField(max_length=32, unique=True)),
                ('key', models.CharField(max_length=64)),
                ('descripcio', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Comerç',
                'verbose_name_plural': 'Comerços',
            },
        ),
        migrations.CreateModel(
            name='QuotaPagament',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sortides.pagament',),
        ),
        migrations.CreateModel(
            name='SortidaPagament',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sortides.pagament',),
        ),
        migrations.AlterField(
            model_name='pagament',
            name='sortida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.Sortida'),
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importQuota', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('dataLimit', models.DateField(null=True)),
                ('any', models.IntegerField(default=2020)),
                ('descripcio', models.CharField(blank=True, max_length=200)),
                ('comerç', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sortides.Comerç')),
                ('curs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alumnes.Curs')),
            ],
            options={
                'verbose_name': 'Quota',
                'verbose_name_plural': 'Quotes',
                'ordering': ['any', 'curs'],
            },
        ),
        migrations.AddField(
            model_name='pagament',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.Quota'),
        ),
        migrations.AddField(
            model_name='sortida',
            name='comerç',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.Comerç'),
        ),
    ]
