# Generated by Django 3.2 on 2021-04-17 13:23

import aula.apps.sortides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0023_auto_20201220_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='any',
            field=models.IntegerField(default=aula.apps.sortides.models.return_any_actual),
        ),
        migrations.AlterField(
            model_name='quota',
            name='dataLimit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
