# Generated by Django 3.0.6 on 2020-06-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0023_auto_20200620_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='es_taxa',
            field=models.BooleanField(default=False),
        ),
    ]
