# Generated by Django 3.0.6 on 2020-06-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0024_quota_es_taxa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quota',
            options={'ordering': ['any', 'curs__nom_curs_complert'], 'verbose_name': 'Quota', 'verbose_name_plural': 'Quotes'},
        ),
    ]
