# Generated by Django 4.0.2 on 2022-07-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0025_pagament_observacions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='mitja_de_transport',
            field=models.CharField(choices=[('TR', 'Tren'), ('BU', 'Bus'), ('AP', 'A peu'), ('CO', 'Combinat'), ('ND', 'No cal desplaçament'), ('MP', 'Mitjans propis')], help_text='Tria el mitjà de transport', max_length=2),
        ),
    ]
