# Generated by Django 3.0.6 on 2020-06-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0025_auto_20200623_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagament',
            name='fracciona',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='pagament',
            name='importParcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
