# Generated by Django 3.2.16 on 2022-12-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0026_alter_sortida_mitja_de_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='condicions_generals',
            field=models.TextField(blank=True, help_text='Aquesta informació arriba a les famílies. Indica què cal portar (boli, llibreta, portàtil,...), recomanacions (crema solar, gorra, insecticida, ...),  menjar i beguda,...  Si no cal portar res cal indicar-ho.'),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='programa_de_la_sortida',
            field=models.TextField(help_text="Aquesta informació arriba a les famílies. Descriu l'activitat incloent altres informacions d'interès (desenvolupament, tipus d'activitat, horaris, objectius, ...)", verbose_name="Descripció de l'activitat"),
        ),
    ]
