# Generated by Django 3.2.16 on 2023-01-26 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0027_auto_20221207_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='tipus',
            field=models.CharField(choices=[('E', 'Excursió - sortida'), ('X', 'Xerrada'), ('G', 'Pagament'), ('P', 'Parlament Verd'), ('A', 'Altres (especificar-ho al títol)')], default='E', help_text="Tipus d'activitat", max_length=1),
        ),
    ]
