# Generated by Django 3.2.18 on 2023-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0028_alter_sortida_tipus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='alumnes_a_l_aula_amb_professor_titular',
            field=models.BooleanField(default=False, help_text="Els alumnes seran a l'aula i el professor de l'hora corresponent passarà llista com fa habitualment.", verbose_name="Passar llista durant l'activitat"),
        ),
    ]
