# Generated by Django 3.0.6 on 2020-07-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0013_nivell_taxes'),
        ('sortides', '0028_auto_20200701_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagament',
            name='alumne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='alumnes.Alumne'),
        ),
    ]
