# Generated by Django 3.0.6 on 2020-07-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0029_auto_20200706_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagament',
            name='estat',
            field=models.CharField(blank=True, default='', max_length=1, null=True),
        ),
    ]
