# Generated by Django 3.2.18 on 2024-02-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0033_alter_sortida_estat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='subtipus',
            field=models.CharField(choices=[('AS', 'Sortida'), ('AX', 'Xerrada'), ('AT', 'Taller'), ('AA', 'Altres'), ('PD', 'Dossier'), ('PM', 'Material'), ('PA', 'Matrícula'), ('PP', 'Pagament parcial')], default='AS', help_text="Subtipus d'activitat", max_length=2),
        ),
    ]
