# Generated by Django 4.2.1 on 2024-02-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0035_alter_sortida_empresa_de_transport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortida',
            name='empresa_de_transport',
            field=models.CharField(blank=True, default='', help_text="Indica el nom de l'empresa de transports i número de contracte/pressupost.", max_length=250),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='feina_per_als_alumnes_aula',
            field=models.TextField(blank=True, default='', help_text="Descriu o comenta on els professors trobaran la feina que han de fer els alumnes que es quedin a l'aula. Si no queden alumnes a l'aula indica-ho."),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='pagament_a_altres_empreses',
            field=models.TextField(blank=True, default='', help_text="Indica la quantitat, l'empresa que ha de rebre els diners, el sistema de pagament, el número de contracte i el termini. Si no s'ha de pagar res indica-ho, escriu 'res'."),
        ),
        migrations.AlterField(
            model_name='sortida',
            name='pagament_a_empresa_de_transport',
            field=models.CharField(blank=True, default='', help_text="Indica la quantitat que ha de pagar l'institut pel lloguer del bus, o compra de bitllets. Si no ha de pagar res indica-ho, escriu 'res'.", max_length=100),
        ),
    ]
