# Generated by Django 5.2.10 on 2026-02-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sortides", "0039_pagament_notificacions_familia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificasortida",
            name="relacio_familia_notificada",
        ),
        migrations.RemoveField(
            model_name="notificasortida",
            name="relacio_familia_revisada",
        ),
    ]
