# Generated by Django 3.2.5 on 2021-07-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPendent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('fromemail', models.CharField(blank=True, max_length=100, null=True)),
                ('toemail', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
