# Generated by Django 5.0.9 on 2025-02-18 10:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0018_alumne_usuaris_app_associats'),
        ('relacioFamilies', '0002_alter_emailpendent_toemail_docattach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('nom', models.CharField(max_length=240, verbose_name='Nom')),
                ('cognoms', models.CharField(max_length=240, verbose_name='Cognoms')),
                ('parentiu', models.CharField(blank=True, max_length=20, verbose_name='Parentiu')),
                ('localitat', models.CharField(blank=True, max_length=240)),
                ('municipi', models.CharField(blank=True, max_length=240)),
                ('cp', models.CharField(blank=True, max_length=240)),
                ('adreca', models.CharField(blank=True, max_length=250)),
                ('telefon', models.CharField(blank=True, db_index=True, max_length=250)),
                ('correu', models.CharField(blank=True, max_length=240)),
                ('data_alta', models.DateField(default=django.utils.timezone.now)),
                ('data_baixa', models.DateField(blank=True, null=True)),
                ('correu_relacio_familia', models.EmailField(blank=True, help_text='Correu de notificacions', max_length=254, verbose_name='Correu Notifi. Tutors')),
                ('relacio_familia_darrera_notificacio', models.DateTimeField(blank=True, null=True)),
                ('periodicitat_faltes', models.IntegerField(choices=[(0, 'No notificar'), (1, 'Un dia'), (2, 'Dos dies'), (3, 'Tres dies'), (7, 'Una setmana')], default=1, help_text='Interval de temps mínim entre dues notificacions')),
                ('periodicitat_incidencies', models.BooleanField(choices=[(False, 'No notificar.'), (True, 'Notificar-les totes.')], default=True, help_text='Periodicitat en la notificació de les incidències.')),
                ('motiu_bloqueig', models.CharField(blank=True, max_length=250)),
                ('alumnes_associats', models.ManyToManyField(related_name='responsables', to='alumnes.alumne')),
                ('user_associat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['cognoms', 'nom'],
            },
        ),
    ]
