# Generated by Django 5.1.6 on 2025-03-01 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relacioFamilies', '0003_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='relacio_familia_darrera_notificacio',
        ),
    ]
