# Generated by Django 5.0.9 on 2024-11-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0018_alumne_usuaris_app_associats'),
        ('relacioFamilies', '0003_responsable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsable',
            name='alumne_actual',
        ),
        migrations.AlterField(
            model_name='responsable',
            name='alumnes_associats',
            field=models.ManyToManyField(related_name='responsables', to='alumnes.alumne'),
        ),
    ]
