version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_NAME}

  web:
    image: django_aula:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command:
      - invoke
      - wait-for
      - db:5432
      - makemigrations
      - migrate
      - --noinput
      - runserver
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db