# docker/Dockerfile.demo.automatica
FROM python:3.13-slim

WORKDIR /app

# Copiem el codi font
COPY . /app

# Instal·lació de dependències del sistema
RUN apt update && apt install --no-install-recommends --no-install-suggests -y \
    bash \
    curl \
    libgl1 \
    libglib2.0-0 \
    libpq-dev \
    zlib1g-dev && \
    curl -sSL https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh -o /usr/local/bin/wait-for-it && \
    chmod +x /usr/local/bin/wait-for-it && \
    apt clean && rm -rf /var/lib/apt/lists/*

# Instal·lació de dependències Python
RUN pip install --upgrade pip && pip install -r requirements.txt
