# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aules', '0002_auto_20180411_1918'),
        ('horaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horari',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aules.Aula'),
        ),
    ]
