# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aules', '0003_auto_20180207_1916'),
        ('horaris', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horari',
            name='nom_aula',
        ),
        migrations.AddField(
            model_name='horari',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aules.Aula'),
        ),
    ]
