# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horaris', '0002_horari_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horari',
            name='aula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aules.Aula'),
        ),
    ]
