# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aules', '0004_auto_20180214_1932'),
        ('presencia', '0003_choicesnohadeseralaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='impartir',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aules.ReservaAula'),
        ),
    ]
