# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 19:45
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("presencia", "0004_impartir_reserva"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impartir",
            name="reserva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="aules.ReservaAula",
            ),
        ),
    ]
