# Generated by Django 2.2.3 on 2019-10-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presencia', '0007_auto_20191013_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impartir',
            name='horari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horaris.Horari'),
        ),
    ]
