# Generated by Django 3.2.25 & Django 5.1.3 on 2024-11-16 12:41

from django.db import migrations, models
import django

class Migration(migrations.Migration):

    dependencies = [
        ('presencia', '0011_alter_controlassistencia_index_together'),
    ]

    if django.get_version() < '4.1':
        operations = [
            migrations.RemoveIndex(
                model_name='controlassistencia',
                name='presencia_controlassiste_alumne_id_estat_id_relac_8957bdde_idx',
            ),
            migrations.AddIndex(
                model_name='controlassistencia',
                index=models.Index(fields=['alumne', 'estat', 'relacio_familia_notificada'], name='presencia_c_alumne__6961f9_idx'),
            ),
        ]
    if django.get_version() >= '4.1':
        operations = [
        migrations.RenameIndex(
            model_name='controlassistencia',
            new_name='presencia_c_alumne__6961f9_idx',
            old_name='presencia_controlassiste_alumne_id_estat_id_relac_8957bdde_idx',
        ),
        ]
