# Generated by Django 5.0.9 on 2024-11-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencia', '0011_alter_controlassistencia_index_together'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='controlassistencia',
            new_name='presencia_c_alumne__6961f9_idx',
            old_fields=('alumne', 'estat', 'relacio_familia_notificada'),
        ),
        migrations.AddField(
            model_name='controlassistencia',
            name='moment',
            field=models.DateTimeField(null=True),
        ),
    ]
