# Generated by Django 5.0.9 on 2025-02-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presencia', '0013_remove_controlassistencia_presencia_c_alumne__6961f9_idx_and_more'),
        ('usuaris', '0014_notifusuari'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlassistencia',
            name='notificacions_familia',
            field=models.ManyToManyField(db_index=True, to='usuaris.notifusuari'),
        ),
    ]
