# Generated by Django 5.2.10 on 2026-02-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presencia", "0014_controlassistencia_notificacions_familia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="controlassistencia",
            name="relacio_familia_notificada",
        ),
        migrations.RemoveField(
            model_name="controlassistencia",
            name="relacio_familia_revisada",
        ),
    ]
