# Generated by Django 2.2 on 2020-02-04 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('horaris', '0005_auto_20191009_1056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_recurs', models.CharField(blank=True, max_length=45)),
                ('descripcio_recurs', models.CharField(blank=True, help_text='Exemple: Armari amb 16 portàtils Windows 10. Exemple: Equip de so i vídeo', max_length=240)),
                ('horari_lliure', models.BooleanField(default=False, help_text='Permet reserves amb temps fraccionat')),
                ('reservable', models.BooleanField(default=True)),
                ('disponibilitat_horaria', models.ManyToManyField(blank=True, help_text='Deixar en blanc per a qualsevol hora en que hi hagi docència al centre.', to='horaris.FranjaHoraria')),
            ],
            options={
                'verbose_name': 'Recurs',
                'verbose_name_plural': 'Recursos',
                'ordering': ['nom_recurs'],
            },
        ),
        migrations.CreateModel(
            name='ReservaRecurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_reserva', models.DateField()),
                ('hora_inici', models.TimeField()),
                ('hora_fi', models.TimeField()),
                ('motiu', models.CharField(help_text="Explica el propòsit de la reserva.\n                             (Ex: Projecció vídeo.)\n                             (Ex: Treball online.)\n                             Important: No entreu dades sensibles en aquest camp, no entreu noms d'alumnes ni noms de famílies,\n                             la primera frase d'una reserva pot ser pública a tothom.", max_length=120)),
                ('es_reserva_manual', models.BooleanField(default=False, editable=False, help_text="la reserva s'ha fet manualment")),
                ('hora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='horaris.FranjaHoraria', verbose_name='Franja Horaria')),
                ('recurs', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.Recurs')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dia_reserva', 'hora'],
            },
        ),
        migrations.AddIndex(
            model_name='reservarecurs',
            index=models.Index(fields=['dia_reserva', 'hora'], name='material_re_dia_res_56e20f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservarecurs',
            index=models.Index(fields=['es_reserva_manual', 'usuari', 'dia_reserva', 'hora'], name='material_re_es_rese_f21324_idx'),
        ),
    ]
