# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aules', '0003_auto_20180207_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='disponibilitat_horaria',
            field=models.ManyToManyField(blank=True, to='horaris.FranjaHoraria'),
        ),
    ]
