# Generated by Django 2.2.3 on 2019-10-09 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnes', '0009_auto_20190331_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agrupament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_alumnes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grup_alumnes', to='alumnes.Grup')),
                ('grup_horari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grup_horari', to='alumnes.Grup')),
            ],
            options={
                'verbose_name': 'Parella agrupament N-M entre grups alumnes i grups horari',
                'verbose_name_plural': 'Agrupaments N-M entre grups alumnes i grups horari',
                'ordering': ['grup_alumnes', 'grup_horari'],
            },
        ),
    ]
