# Generated by Django 2.2.6 on 2019-10-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0004_auto_20190924_1045'),
        ('usuaris', '0006_auto_20191013_1050'),
    ]

    operations = [
    ]
