# Generated by Django 2.2.6 on 2020-04-05 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0008_auto_20191027_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accio',
            name='tipus',
            field=models.CharField(choices=[('PL', 'Passar llista'), ('LL', 'Posar o treure alumnes a la llista'), ('IN', 'Posar o treur Incidència'), ('EE', 'Editar Expulsió'), ('EC', 'Expulsar del Centre'), ('RE', 'Recullir expulsió'), ('AC', 'Registre Actuació'), ('AG', 'Actualitza alumnes des de Saga'), ('MT', 'Envia missatge a tutors'), ('SK', 'Sincronitza Kronowin'), ('JF', 'Justificar Faltes'), ('NF', 'Notificacio Families'), ('AS', 'Accés a dades sensibles'), ('SU', 'Sincronitza Untis'), ('DS', 'Control Delivery Status Notification')], max_length=2),
        ),
    ]
