# Generated by Django 3.2.11 on 2022-04-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0016_merge_20210830_1954'),
        ('usuaris', '0010_dadesaddicionalsprofessor_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractModificationPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darrera_sincronitzacio', models.DateTimeField(blank=True, null=True)),
                ('novetats_detectades_moment', models.DateTimeField(blank=True, null=True)),
                ('alumne_referenciat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='modificacions_portal_set', related_query_name='modificacions_portal', to='alumnes.alumne')),
            ],
        ),
        migrations.CreateModel(
            name='ModificationPortal',
            fields=[
                ('abstractmodificationportal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuaris.abstractmodificationportal')),
            ],
            bases=('usuaris.abstractmodificationportal',),
        ),
    ]
