# Generated by Django 3.2.18 on 2023-03-16 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumnes", "0017_nivell_preexclusiva"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuaris", "0010_dadesaddicionalsprofessor_foto"),
    ]

    operations = [
    ]
