# Generated by Django 3.2.18 on 2023-03-16 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0017_nivell_preexclusiva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuaris', '0010_dadesaddicionalsprofessor_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_expedicio', models.DateTimeField(auto_now_add=True)),
                ('moment_captura', models.DateTimeField(blank=True, null=True, unique=True)),
                ('moment_confirmat_pel_tutor', models.DateTimeField(blank=True, null=True)),
                ('darrera_sincronitzacio', models.DateTimeField(blank=True, null=True)),
                ('novetats_detectades_moment', models.DateTimeField(blank=True, null=True)),
                ('clau', models.CharField(db_index=True, max_length=40)),
                ('localitzador', models.CharField(db_index=True, default='-', max_length=4, unique=True)),
                ('es_el_token_actiu', models.BooleanField(default=False)),
                ('alumne_referenciat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_portal_set', related_query_name='qr_portal', to='alumnes.alumne')),
                ('usuari_referenciat',models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
