# Generated by Django 3.2.16 on 2022-12-13 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnes', '0017_nivell_preexclusiva'),
        ('usuaris', '0010_dadesaddicionalsprofessor_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractQRPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment_expedicio', models.DateTimeField(auto_now_add=True)),
                ('moment_captura', models.DateTimeField(blank=True, null=True)),
                ('clau', models.CharField(max_length=40)),
                ('numero_de_mobil', models.CharField(blank=True, max_length=40)),
                ('alumne_referenciat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_portal_set', related_query_name='qr_portal', to='alumnes.alumne')),
                ('usuari_referenciat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QRPortal',
            fields=[
                ('abstractqrportal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuaris.abstractqrportal')),
            ],
            bases=('usuaris.abstractqrportal',),
        ),
    ]
