# Generated by Django 3.2.16 on 2022-12-14 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuaris', '0011_abstractqrportal_qrportal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractqrportal',
            name='numero_de_mobil',
        ),
        migrations.AddField(
            model_name='abstractqrportal',
            name='darrera_sincronitzacio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractqrportal',
            name='es_el_token_actiu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='abstractqrportal',
            name='localitzador',
            field=models.CharField(db_index=True, default='-', max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='abstractqrportal',
            name='moment_confirmat_pel_tutor',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractqrportal',
            name='novetats_detectades_moment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractqrportal',
            name='clau',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='abstractqrportal',
            name='moment_captura',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='abstractqrportal',
            name='usuari_referenciat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
