# Generated by Django 5.0.9 on 2024-10-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuaris', '0012_qrportal_numero_de_mobil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsableUser',
            fields=[
            ],
            options={
                'ordering': ['last_name', 'first_name', 'username'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
        ),
    ]
