# Generated by Django 5.0.9 on 2024-11-06 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0018_alumne_usuaris_app_associats'),
        ('usuaris', '0013_responsableuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotifUsuari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moment', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tipus', models.CharField(blank=True, max_length=1)),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotifUsuari', to='alumnes.alumne')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='NotifUsuari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificació a usuari',
                'verbose_name_plural': 'Notificacions als usuaris',
                'ordering': ['usuari', '-moment'],
                'abstract': False,
                'indexes': [models.Index(fields=['usuari', 'alumne', 'tipus'], name='usuaris_not_usuari__70cc4d_idx')],
            },
        ),
    ]
