# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencies', '0003_incidencia_gestionada_pel_tutor_motiu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='gestionada_pel_tutor',
            field=models.BooleanField(default=False, editable=False, help_text='Aquesta incid\xe8ncia podr\xe0 ser gestionada pel tutor.".', verbose_name='Incid\xe8ncia pot ser gestionada pel tutor'),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='gestionada_pel_tutor_motiu',
            field=models.CharField(choices=[('1AHora', 'Pot ser gestionada pel tutor: Retard de 1a hora'), ('ForaAula', "Pot ser gestionada pel tutor: Incid\xe8ncia fora d'aula"), ('Guardia', 'Pot ser gestionada pel tutor: Incid\xe8ncia en hora de Gu\xe0rdia'), ('N/A', 'Pot ser gestionada pel tutor')], default=b'', editable=False, max_length=20),
        ),
    ]
