# Generated by Django 5.2.10 on 2026-02-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidencies", "0009_expulsio_notificacions_familia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expulsio",
            name="relacio_familia_notificada",
        ),
        migrations.RemoveField(
            model_name="expulsio",
            name="relacio_familia_revisada",
        ),
        migrations.RemoveField(
            model_name="incidencia",
            name="relacio_familia_notificada",
        ),
        migrations.RemoveField(
            model_name="incidencia",
            name="relacio_familia_revisada",
        ),
        migrations.RemoveField(
            model_name="sancio",
            name="relacio_familia_notificada",
        ),
        migrations.RemoveField(
            model_name="sancio",
            name="relacio_familia_revisada",
        ),
    ]
