# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0002_auto_20160226_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaabsentisme',
            name='faltes_des_de_data',
            field=models.DateField(default=b'2018-09-17', editable=False, verbose_name=b'Faltes des de data'),
        ),
    ]
