# Generated by Django 3.2.18 on 2023-09-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0006_auto_20210531_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuacio',
            name='assumpte',
            field=models.CharField(choices=[('T', 'Tutoria individualitzada'), ('C', '(PSI) Conflicte comportament'), ('V', '(PSI) Valoració'), ('S', '(PSI) Seguiment'), ('O', '(PSI) Orientació acadèmica'), ('E', '(PSI) Suport educatiu'), ('G', '(PSI) Gestió de les emocions'), ('I', '(PSI) Gestió social'), ('P', '(PSI) Pla individualitzat'), ('A', 'Actuació puntual'), ('F', 'Entrevista Família')], help_text='Assumpte', max_length=1),
        ),
    ]
