# Generated by Django 3.2.18 on 2024-08-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0007_alter_actuacio_assumpte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaabsentisme',
            name='avisat_tutor',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
