# Generated by Django 3.2.18 on 2024-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoria', '0008_cartaabsentisme_avisat_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaabsentisme',
            name='data_carta',
            field=models.DateField(null=True, verbose_name='Data de la carta'),
        ),
    ]
