# Generated by Django 4.2.15 on 2024-11-25 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tutoria", "0009_alter_cartaabsentisme_data_carta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartaabsentisme",
            name="avisat_tutor",
        ),
    ]
