# Generated by Django 3.0.6 on 2020-06-23 17:30

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dades',
            name='files',
            field=private_storage.fields.PrivateFileField(help_text='Documentació obligatòria', null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='matricula/%Y/', verbose_name='Fitxer amb documents'),
        ),
    ]
