# Generated by Django 5.0.9 on 2024-11-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matricula', '0002_alter_matricula_adreca_alter_matricula_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='rp1_adreca',
            field=models.CharField(blank=True, max_length=250, verbose_name='Adreça'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp1_cognoms',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cognoms'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp1_cp',
            field=models.CharField(blank=True, max_length=10, verbose_name='Codi postal'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp1_dni',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Dni'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp1_localitat',
            field=models.CharField(blank=True, max_length=240, verbose_name='Localitat'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp1_parentiu',
            field=models.CharField(blank=True, max_length=20, verbose_name='Parentiu'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp2_adreca',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Adreça'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp2_cognoms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cognoms'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp2_cp',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codi postal'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp2_dni',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Dni'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp2_localitat',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Localitat'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='rp2_parentiu',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Parentiu'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='localitat',
            field=models.CharField(blank=True, default='', max_length=240, verbose_name='Localitat'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='rp1_correu',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Correu'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='rp1_nom',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='rp1_telefon',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telèfon'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='rp2_correu',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correu'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='rp2_nom',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='rp2_telefon',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telèfon'),
        ),
    ]
