# Generated by Django 3.0.6 on 2020-06-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sortides', '0025_auto_20200623_1730'),
        ('alumnes', '0012_nivell_matricula_oberta'),
        ('matricula', '0002_auto_20200623_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticio',
            name='alumne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alumnes.Alumne'),
        ),
        migrations.AlterField(
            model_name='peticio',
            name='dades',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='matricula.Dades'),
        ),
        migrations.AlterField(
            model_name='peticio',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sortides.Quota'),
        ),
    ]
