# Generated by Django 5.1.15 on 2026-03-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matricula", "0003_matricula_rp1_adreca_matricula_rp1_cognoms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="matricula",
            name="curs_complet",
            field=models.BooleanField(
                default=False,
                help_text="Matrícula típica de tots els mòduls",
                verbose_name="Matrícula del curs complet",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="llistaufs",
            field=models.CharField(
                blank=True,
                help_text="En cas de mòduls solts",
                max_length=250,
                null=True,
                verbose_name="Mòduls de la matrícula",
            ),
        ),
        migrations.AlterField(
            model_name="matricula",
            name="quantitat_ufs",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                verbose_name="Mòduls solts, curs no complet",
            ),
        ),
    ]
