# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-12 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0007_alumne_municipi'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='cp',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
