# Generated by Django 2.1.7 on 2019-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0008_alumne_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='cognoms',
            field=models.CharField(max_length=240, verbose_name='Cognoms'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='data_neixement',
            field=models.DateField(null=True, verbose_name='Data naixement'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='estat_sincronitzacio',
            field=models.CharField(blank=True, choices=[('PRC', 'En procés de sincronització'), ('S-I', 'Sincronitzat Insert'), ('S-U', 'Sincronitzat Update'), ('DEL', 'Alumne donat de baixa'), ('MAN', "Alumne donat d'alta manualment")], max_length=3),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='nom',
            field=models.CharField(max_length=240, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='periodicitat_faltes',
            field=models.IntegerField(choices=[(0, 'No notificar'), (1, 'Un dia'), (2, 'Dos dies'), (3, 'Tres dies'), (7, 'Una setmana')], default=1, help_text='Interval de temps mínim entre dues notificacions'),
        ),
        migrations.AlterField(
            model_name='alumne',
            name='periodicitat_incidencies',
            field=models.BooleanField(choices=[(False, 'No notificar.'), (True, 'Notificar-les totes.')], default=True, help_text='Periodicitat en la notificació de les incidències.'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='data_fi_curs',
            field=models.DateField(blank=True, help_text="Dia que finalitzen les classes (es poden posar dies festius a l'apartat corresponent)", null=True, verbose_name='Acaben'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='data_inici_curs',
            field=models.DateField(blank=True, help_text='Dia que comencen les classes (cal informar aquest cap per poder fer control de presència)', null=True, verbose_name='Comencen'),
        ),
        migrations.AlterField(
            model_name='curs',
            name='nom_curs',
            field=models.CharField(help_text='Un número que representa el curs (Ex: 3)', max_length=45, verbose_name='Nom curs'),
        ),
        migrations.AlterField(
            model_name='nivell',
            name='nom_nivell',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nom nivell'),
        ),
    ]
