# Generated by Django 2.2 on 2019-09-03 12:37

import aula.apps.alumnes.abstract_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0009_auto_20190331_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='foto',
            field=models.ImageField(blank=True, max_length=1024, null=True, upload_to=aula.apps.alumnes.abstract_models.AbstractAlumne.user_directory_path),
        ),
    ]
