# Generated by Django 2.2 on 2019-09-27 10:13

from django.db import migrations
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0009_auto_20190331_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='foto',
            field=private_storage.fields.PrivateFileField(null=True, storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='alumnes/fotos', verbose_name='Foto'),
        ),
    ]
