# Generated by Django 2.2 on 2020-05-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0011_auto_20191002_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='primer_responsable',
            field=models.IntegerField(default=1),
        ),
    ]
