# Generated by Django 3.0.6 on 2020-06-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0011_auto_20191002_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivell',
            name='matricula_oberta',
            field=models.BooleanField(default=False),
        ),
    ]
