# Generated by Django 3.0.6 on 2020-07-10 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0013_alumne_observacions'),
        ('alumnes', '0013_nivell_taxes'),
    ]

    operations = [
    ]
