# Generated by Django 3.1.6 on 2021-08-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0014_auto_20210501_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='autoritzacio_sortides',
            field=models.BooleanField(blank=True, choices=[(True, 'SÍ'), (False, 'NO')], help_text='Autorització per realitzar sortides', null=True),
        ),
        migrations.AddField(
            model_name='alumne',
            name='dades_mediques',
            field=models.CharField(blank=True, max_length=750),
        ),
        migrations.AddField(
            model_name='alumne',
            name='drets_imatge',
            field=models.BooleanField(blank=True, choices=[(True, 'SÍ'), (False, 'NO')], help_text="Acceptació dels drets d'imatge", null=True),
        ),
        migrations.AddField(
            model_name='alumne',
            name='rp_importat_nom',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='alumne',
            name='salut_i_escola',
            field=models.BooleanField(blank=True, choices=[(True, 'SÍ'), (False, 'NO')], help_text='Acceptació del programa Salut i Escola', null=True),
        ),
    ]
