# Generated by Django 3.2.5 on 2021-08-30 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0015_auto_20210726_0121'),
        ('alumnes', '0015_dadesaddicionalsalumne'),
    ]

    operations = [
    ]
