# Generated by Django 3.2.18 on 2023-04-13 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuaris', '0012_qrportal_numero_de_mobil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alumnes', '0017_nivell_preexclusiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='usuaris_app_associats',
            field=models.ManyToManyField(related_name='alumne_app_set', related_query_name='alumne_app', through='usuaris.QRPortal', to=settings.AUTH_USER_MODEL),
        ),
    ]
