# Generated by Django 3.2.16 on 2022-12-13 17:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuaris', '0011_abstractqrportal_qrportal'),
        ('alumnes', '0017_nivell_preexclusiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='usuaris_app_associats',
            field=models.ManyToManyField(related_name='alumne_app_set', related_query_name='alumne_app', through='usuaris.QRPortal', to=settings.AUTH_USER_MODEL),
        ),
    ]
