# Generated by Django 3.2.25 on 2025-02-08 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relacioFamilies', '0004_remove_responsable_alumne_actual_and_more'),
        ('alumnes', '0018_alumne_usuaris_app_associats'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='responsable_preferent',
            field=models.ForeignKey(help_text="Responsable preferent de l'alumne/a", null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacioFamilies.responsable'),
        ),
    ]
