# Generated by Django 5.0.9 on 2025-02-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0018_alumne_usuaris_app_associats'),
        ('relacioFamilies', '0003_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumne',
            name='responsable_preferent',
            field=models.ForeignKey(help_text="Responsable preferent de l'alumne/a", null=True, on_delete=django.db.models.deletion.SET_NULL, to='relacioFamilies.responsable'),
        ),
    ]
