# Generated by Django 5.1.6 on 2025-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnes', '0019_alumne_responsable_preferent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumne',
            name='tutors_volen_rebre_correu',
            field=models.BooleanField(null=True),
        ),
    ]
