# Generated by Django 5.1.5 on 2025-07-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumnes", "0021_alumne_aruco_marker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumne",
            name="aruco_marker",
            field=models.IntegerField(
                default=-1,
                help_text="Identificador del marker ARUCO associat a l'alumne. Ha de ser únic dins el nivell (Eso, Btx, ...) Del 0 al 99 per assignació manual",
                verbose_name="Marker",
            ),
            preserve_default=False,
        ),
    ]
