# Generated by Django 5.2.10 on 2026-02-03 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alumnes", "0023_alter_alumne_aruco_marker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alumne",
            name="correu_relacio_familia_mare",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="correu_relacio_familia_pare",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="correu_tutors",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="primer_responsable",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="relacio_familia_darrera_notificacio",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="rp1_correu",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="rp1_mobil",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="rp1_nom",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="rp1_telefon",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="rp2_correu",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="rp2_mobil",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="rp2_nom",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="rp2_telefon",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="telefons",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="tutors",
        ),
        migrations.RemoveField(
            model_name="alumne",
            name="tutors_volen_rebre_correu",
        ),
    ]
